-- Creating the CUSTOMER Table
CREATE TABLE CUSTOMER (
    CUST_NO CHAR(5) CONSTRAINT PK_CUSTOMER PRIMARY KEY CHECK (CUST_NO LIKE 'C____'),
    NAME VARCHAR2(100) NOT NULL,
    PHONE_NO VARCHAR2(15),
    CITY VARCHAR2(50) NOT NULL
);

-- Creating the BRANCH Table
CREATE TABLE BRANCH (
    BRANCH_CODE CHAR(4) CONSTRAINT PK_BRANCH PRIMARY KEY,
    BRANCH_NAME VARCHAR2(100) NOT NULL,
    BRANCH_CITY VARCHAR2(50) CHECK (BRANCH_CITY IN ('DELHI', 'MUMBAI', 'KOLKATA', 'CHENNAI'))
);

-- Creating the ACCOUNT Table
CREATE TABLE ACCOUNT (
    ACCOUNT_NO CHAR(5) CONSTRAINT PK_ACCOUNT PRIMARY KEY CHECK (ACCOUNT_NO LIKE 'A____'),
    TYPE VARCHAR2(2) CHECK (TYPE IN ('SB', 'FD', 'CA')),
    BALANCE NUMBER(10,2) CHECK (BALANCE < 10000000),
    BRANCH_CODE CHAR(4) CONSTRAINT FK_ACCOUNT_BRANCH REFERENCES BRANCH(BRANCH_CODE)
);

-- Creating the DEPOSITOR Table
CREATE TABLE DEPOSITOR (
    CUST_NO CHAR(5) CONSTRAINT FK_DEPOSITOR_CUSTOMER REFERENCES CUSTOMER(CUST_NO),
    ACCOUNT_NO CHAR(5) CONSTRAINT FK_DEPOSITOR_ACCOUNT REFERENCES ACCOUNT(ACCOUNT_NO),
    CONSTRAINT PK_DEPOSITOR PRIMARY KEY (CUST_NO, ACCOUNT_NO)
);

-- Creating the LOAN Table
CREATE TABLE LOAN (
    LOAN_NO CHAR(5) CONSTRAINT PK_LOAN PRIMARY KEY CHECK (LOAN_NO LIKE 'L____'),
    CUST_NO CHAR(5) CONSTRAINT FK_LOAN_CUSTOMER REFERENCES CUSTOMER(CUST_NO),
    AMOUNT NUMBER(10,2) CHECK (AMOUNT > 1000),
    BRANCH_CODE CHAR(4) CONSTRAINT FK_LOAN_BRANCH REFERENCES BRANCH(BRANCH_CODE)
);

-- Creating the INSTALLMENT Table
CREATE TABLE INSTALLMENT (
    INST_NO NUMBER(2) CHECK (INST_NO <= 10),
    LOAN_NO CHAR(5) CONSTRAINT FK_INSTALLMENT_LOAN REFERENCES LOAN(LOAN_NO),
    INST_AMOUNT NUMBER(10,2) NOT NULL,
    CONSTRAINT PK_INSTALLMENT PRIMARY KEY (INST_NO, LOAN_NO)
);
